version: '3.3'

services:
  influxdb:
    image: influxdb:2.7.4
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=initialpassword
      - DOCKER_INFLUXDB_INIT_ORG=ff-rancilio-mods 
      - DOCKER_INFLUXDB_INIT_BUCKET=rancilio
    restart: unless-stopped
  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=initialpassword

volumes:
    influxdb-storage:
    grafana-storage: